# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches:
      - master
jobs:
  testPipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: test running python script
        run: python test.py

      - name: Commit changes
        run: |
          git config --global user.name 'Nirmal'
          git config --global user.email 'nirmalp2@illinois.edu'
          git commit -am "Update secret"
          git push
